//
// Created by igor on 06.03.18.
//

#ifndef JIMP_EXERCISES_MULTIPLICATIONTABLE_H
#define JIMP_EXERCISES_MULTIPLICATIONTABLE_H

void MultiplicationTable(int tab[][10]);


#endif //JIMP_EXERCISES_MULTIPLICATIONTABLE_H
